### ISSUE TITLE
pandoc

### ISSUE THREAD

**Issue by AtomicNess123** [karlicoss/orger#15]
Could I use orger to convert from docx or odt to org, just like pandoc?

**Comment by karlicoss** [comment]
Hi, what do you mean? Why don't you just use pandoc directly? :)

**Comment by AtomicNess123** [comment]
I was curious how the results would compare or whether you use pandoc in your algorithms.

**Comment by karlicoss** [comment]
Depends on what you convert! In general docx/odt can be quite sophisticated whereas orger (being org-mode) is a tree-like hierarchy. So in general pandoc would be much better at being close to the original document. What are you trying to achieve?
Yeah I use pandoc in couple of modules, but it's when the input data is in HTML (for example, Polar module), so just to avoid manual filtering on HTML tags.
